# [Bug] 升级 @umijs/plugins 中的 @umijs/valtio 版本

`bug`

<!--
感谢您向我们反馈问题，为了高效的解决问题，我们期望你能提供以下信息：
-->

## What happens?

最新[合并的PR](https://github.com/umijs/umi/pull/10313)，并没有导出`useProxy`。导致`valtio`无法正常使用。

<!-- A clear and concise description of what the bug is. -->
<!-- 清晰的描述下遇到的问题。-->

## Mini Showcase Repository(REQUIRED)

- 参考How To Reproduce

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

<!-- 为节约大家的时间，无复现步骤的 ISSUE 会被关闭，提供之后再 REOPEN -->
<!-- YOUR_REPOSITORY_URL on github or stackbliz -->

## How To Reproduce

<!-- 请提供复现链接/步骤，错误日志以及相关配置 -->

- 干净的部署环境
- `umijs/max` 脚手架初始化
- 开启`valtio`插件
- 项目中使用`valtio`
- 构建部署

```
fatal - Error: ERROR in ./src/.umi-production/plugin-valtio/index.ts 4:0-287
export 'useProxy' (reexported as 'useProxy') was not found in '/Users/../node_modules/.pnpm/@umijs+valtio@1.0.2/node_modules/@umijs/valtio' (possible exports: derive, proxy, proxyMap, proxySet, proxyWithComputed, proxyWithDevtools, proxyWithHistory, snapshot, subscribe, subscribeKey, underive, useSnapshot)
 @ ./src/.umi-production/exports.ts 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255 16:0-255
 @ ./src/.umi-production/umi.ts
```

## Context

- **Umi Version**: "^4.0.47",
- **Node Version**: v16.18.0
- **Platform**: OSX

## fz6m

是的，这个包没发，得发一下。

## fz6m

此问题最新进展：

1. 需要升级 `@umijs/plugins` 中的 `@umijs/valtio` 版本，每次光 `@umijs/valtio` 发版还不够，需要 `@umijs/plugins` 中的版本也跟着提升，否则升级 `umi` / `@umijs/max` 版本的场景（很常见），由于旧的 `@umijs/valtio` 仍满足 `@umijs/plugins` 的 `package.json` 中 `^1.0.2` 的要求，不会得到升级，十分严重的问题。

2. 最好有自动的机制完成
