# [Bug] umi3和umi4 mock返回有问题

## What happens?

在`umi3`中`mock`可以正常返回一个`Response`对象
![QQ图片20230130140842](https://user-images.githubusercontent.com/51755878/215404215-c3d5792f-93b9-41b0-9719-ba6da67c74bf.png)
但是`umi4`中同样的操作却是一个普通`Object` 多次重新构建项目仍然如此
![image](https://user-images.githubusercontent.com/51755878/215404273-5748cf49-d2d7-4a42-b8ea-350b979d50a1.png)

## Context

- **Umi Version**:@umijs/max ^4.0.47

## How To Reproduce

在项目目录下新建`mock`文件夹 然后请求

## xiaohuoni

应该是请求方式从 `umi-request` 缓存 axios 的差异。你这个日志是在哪里打印的？

## Hincex

> 应该是请求方式从 `umi-request` 缓存 axios 的差异。你这个日志是在哪里打印的？

在响应拦截器里打印的
