# 🧐[问题] 升级到 umi3 导出使用 connect 运行报错

`🕵🏻‍♀️ question`

### 🧐 问题描述

升级到 umi 3之后，从 umi 导出 connect，生成成功，运行时报错
TypeError: Object(...) is not a function

### 🚑 其他信息

![image](https://user-images.githubusercontent.com/32095100/77053659-a55ff280-6a09-11ea-9750-0a65d31f9da9.png)
![image](https://user-images.githubusercontent.com/32095100/77053716-b7da2c00-6a09-11ea-93aa-c0117ff51c49.png)
![image](https://user-images.githubusercontent.com/32095100/77053757-c6284800-6a09-11ea-8c60-3b99c0b0b85e.png)

## s464446877

请问你升级到umi3后修改国际化的formatmessage了么

## yunyouu

> 请问你升级到umi3后修改国际化的formatmessage了么

没有呢，是引起这个问题的原因嘛

## s464446877

> > 请问你升级到umi3后修改国际化的formatmessage了么
>
> 没有呢，是引起这个问题的原因嘛

不是，只是我现在升级到umi3后官方不推荐使用formatmessage，按照官方推荐的方式有写地方还不适用，不知道怎么弄，想交流一下

## chenshuai2144

@s464446877 那些地方不适用？

## chenshuai2144

@yanglwr 是不是 dva 插件没有配置？

## ZhengHuang-20

> @yanglwr 是不是 dva 插件没有配置？

你好这个是怎么解决的呢？ 我也遇到了这个问题
import { queryAuthList } from '@/services/auth';
import React, { useEffect } from 'react';
import { connect } from 'umi';
import type { ConnectState } from '@/models/connect';

export type AuthProps = {
authName: string,
showWaring?: boolean,
children: React.ReactElement<AuthProps>[],
authList: []
}
const AuthComponent: React.FC<AuthProps> = (props) => {
const { authName, showWaring, children, authList } = props;

const getChildren = () => {
return queryAuthList().then((authList) => {
const isDenied = !authList[authName];
if (isDenied) {
if (showWaring) {
return <div className="auth_ctrl" >当前用户没有访问权限，请联系管理员开通权限！</div>;
}
return null;
} else {
React.Children.forEach(children, (child: React.ReactElement<AuthProps>): void => {
console.log(child);
})
}
});

}

return <div></div>;

};

export default connect(({ global }: ConnectState) => ({
authList: global.authList
}))(AuthComponent);

报错：
TypeError: Object(...) is not a function

## jackchoumine

报错，没找到解决办法。

## jackchoumine

> ### 问题描述
>
> 升级到 umi 3 之后，从 umi 导出 connect，生成成功，运行时报错
> TypeError: Object(...) is not a function
>
> ### 其他信息
>
> ![image](https://user-images.githubusercontent.com/32095100/77053659-a55ff280-6a09-11ea-9750-0a65d31f9da9.png) > ![image](https://user-images.githubusercontent.com/32095100/77053716-b7da2c00-6a09-11ea-93aa-c0117ff51c49.png) > ![image](https://user-images.githubusercontent.com/32095100/77053757-c6284800-6a09-11ea-8c60-3b99c0b0b85e.png)

请问解决了吗 ？ 如何解决的呢？

## chenshuai2144

打开一下dva，并且写个model。

默认是关闭的

## dingyl666

请问解决了吗，我也遇到这个问题了
