在onSave方法中添加异常处理，当返回错误信息时直接返回即可。例如：

```javascript
const onSave = async (key, row) => {
  try {
    const res = await saveData({ key, row });
    if (res.code !== 0) {
      throw new Error(res.msg);
    }
    // 保存成功才添加行
    const newData = [...data];
    const index = newData.findIndex((item) => key === item.key);
    if (index > -1) {
      const item = newData[index];
      newData.splice(index, 1, { ...item, ...row });
      setData(newData);
    } else {
      newData.push(row);
      setData(newData);
    }
  } catch (err) {
    notification.error({ message: "保存失败", description: err.message });
  }
};
```
